# Generated by Django 4.2 on 2023-05-17 08:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='candidate1',
            field=models.ImageField(default=datetime.datetime(2023, 5, 17, 8, 23, 51, 708366, tzinfo=datetime.timezone.utc), upload_to='candidate1'),
            preserve_default=False,
        ),
    ]
