# Generated by Django 4.2 on 2023-05-17 18:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_image_candidate2_image_candidate3_image_candidate4_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='name',
            field=models.CharField(default=datetime.datetime(2023, 5, 17, 18, 24, 30, 380476, tzinfo=datetime.timezone.utc), max_length=100),
            preserve_default=False,
        ),
    ]
