# Generated by Django 4.2 on 2023-05-17 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_remove_image_name_image_text_input'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='text_input',
        ),
    ]
