# Generated by Django 4.2 on 2023-05-18 05:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_remove_image_text_input'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='name',
            field=models.CharField(default=datetime.datetime(2023, 5, 18, 5, 24, 33, 363894, tzinfo=datetime.timezone.utc), max_length=200),
            preserve_default=False,
        ),
    ]
