# Generated by Django 4.2 on 2023-05-18 05:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_image_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='discription',
            field=models.CharField(default=datetime.datetime(2023, 5, 18, 5, 32, 43, 356178, tzinfo=datetime.timezone.utc), max_length=200),
            preserve_default=False,
        ),
    ]
