# Generated by Django 4.2 on 2023-05-18 05:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_image_discription'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='name_candidate1',
            field=models.CharField(default=datetime.datetime(2023, 5, 18, 5, 55, 8, 666763, tzinfo=datetime.timezone.utc), max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='image',
            name='name_candidate2',
            field=models.CharField(default=datetime.datetime(2023, 5, 18, 5, 55, 31, 240354, tzinfo=datetime.timezone.utc), max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='image',
            name='name_candidate3',
            field=models.CharField(default=datetime.datetime(2023, 5, 18, 5, 55, 34, 860170, tzinfo=datetime.timezone.utc), max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='image',
            name='name_candidate4',
            field=models.CharField(default=datetime.datetime(2023, 5, 18, 5, 55, 39, 182092, tzinfo=datetime.timezone.utc), max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='image',
            name='name_candidate5',
            field=models.CharField(default=datetime.datetime(2023, 5, 18, 5, 55, 43, 537457, tzinfo=datetime.timezone.utc), max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='image',
            name='name_candidate6',
            field=models.CharField(default=datetime.datetime(2023, 5, 18, 5, 55, 48, 464397, tzinfo=datetime.timezone.utc), max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='image',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
