# Generated by Django 4.2 on 2023-05-18 06:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_remove_image_discription_remove_image_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='name_candidate1',
        ),
        migrations.AddField(
            model_name='image',
            name='discription',
            field=models.CharField(default=datetime.datetime(2023, 5, 18, 6, 23, 5, 701323, tzinfo=datetime.timezone.utc), max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='image',
            name='name',
            field=models.CharField(default=datetime.datetime(2023, 5, 18, 6, 23, 33, 249315, tzinfo=datetime.timezone.utc), max_length=200),
            preserve_default=False,
        ),
    ]
