# Generated by Django 4.2 on 2023-05-18 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_remove_image_name_candidate1_image_discription_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='discription',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='image',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
