# Generated by Django 4.2 on 2023-05-18 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_alter_image_discription_alter_image_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='discription',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='image',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
