# Generated by Django 4.2 on 2023-05-18 08:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_alter_image_discription_alter_image_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='name_candidate1',
            field=models.CharField(default=datetime.datetime(2023, 5, 18, 8, 26, 43, 804427, tzinfo=datetime.timezone.utc), max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='image',
            name='name_candidate2',
            field=models.CharField(default=datetime.datetime(2023, 5, 18, 8, 26, 57, 517304, tzinfo=datetime.timezone.utc), max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='image',
            name='name_candidate3',
            field=models.CharField(default=datetime.datetime(2023, 5, 18, 8, 27, 2, 847496, tzinfo=datetime.timezone.utc), max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='image',
            name='name_candidate4',
            field=models.CharField(default=datetime.datetime(2023, 5, 18, 8, 27, 8, 484691, tzinfo=datetime.timezone.utc), max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='image',
            name='name_candidate5',
            field=models.CharField(default=datetime.datetime(2023, 5, 18, 8, 27, 21, 54209, tzinfo=datetime.timezone.utc), max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='image',
            name='name_candidate6',
            field=models.CharField(default=datetime.datetime(2023, 5, 18, 8, 27, 28, 504979, tzinfo=datetime.timezone.utc), max_length=200),
            preserve_default=False,
        ),
    ]
