# Generated by Django 4.2 on 2023-05-20 17:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_image_name_candidate1_image_name_candidate2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='brandtitle',
            field=models.CharField(default=datetime.datetime(2023, 5, 20, 17, 16, 13, 521183, tzinfo=datetime.timezone.utc), max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='image',
            name='votetitle',
            field=models.CharField(default=datetime.datetime(2023, 5, 20, 17, 16, 31, 876393, tzinfo=datetime.timezone.utc), max_length=200),
            preserve_default=False,
        ),
    ]
