# Generated by Django 4.2 on 2023-05-20 17:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_image_brandtitle_image_votetitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='backgroundimg',
            field=models.ImageField(default=datetime.datetime(2023, 5, 20, 17, 39, 10, 194097, tzinfo=datetime.timezone.utc), upload_to='backgroundimg'),
            preserve_default=False,
        ),
    ]
