# Generated by Django 4.2 on 2023-05-21 18:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_candidate_vote_remove_image_name_delete_choice_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='candidate',
        ),
        migrations.AddField(
            model_name='image',
            name='name',
            field=models.CharField(default=datetime.datetime(2023, 5, 21, 18, 6, 35, 455290, tzinfo=datetime.timezone.utc), max_length=200),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Candidate',
        ),
        migrations.DeleteModel(
            name='Vote',
        ),
    ]
