# Generated by Django 4.2 on 2023-05-22 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_candidate_votingsession'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option1_votes', models.PositiveIntegerField(default=0)),
                ('option2_votes', models.PositiveIntegerField(default=0)),
                ('option3_votes', models.PositiveIntegerField(default=0)),
                ('option4_votes', models.PositiveIntegerField(default=0)),
                ('option5_votes', models.PositiveIntegerField(default=0)),
                ('option6_votes', models.PositiveIntegerField(default=0)),
                ('total_votes', models.PositiveIntegerField(default=0)),
                ('option1_percentage', models.FloatField(default=0)),
                ('option2_percentage', models.FloatField(default=0)),
                ('option3_percentage', models.FloatField(default=0)),
                ('option4_percentage', models.FloatField(default=0)),
                ('option5_percentage', models.FloatField(default=0)),
                ('option6_percentage', models.FloatField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='votingsession',
            name='candidates',
        ),
        migrations.DeleteModel(
            name='Candidate',
        ),
        migrations.DeleteModel(
            name='VotingSession',
        ),
    ]
