# Generated by Django 4.2 on 2023-05-23 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_votecount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VoteCount',
        ),
    ]
